all:
  hosts:
    master-1:
      ansible_host: 158.160.12.204
      ansible_user: vm-user
      ip: 192.168.20.21
      etcd_member_name: etcd-1
      
    worker-1:
      ansible_host: 158.160.113.234
      ip: 192.168.10.24
      # access_ip: 158.160.117.200
      ansible_user: vm-user
    
    worker-2:
      ansible_host: 158.160.21.67
      ip: 192.168.20.11
      # access_ip: 158.160.52.213
      ansible_user: vm-user
    
    worker-3:
      ansible_host: 51.250.43.112
      ip: 192.168.30.13
      # access_ip: 158.160.52.213
      ansible_user: vm-user
    
  children:
    kube_control_plane:
      hosts:
        master-1:
  
    kube_node:
      hosts:
        worker-1:
        worker-2:
        worker-3:

    kube_ingress:
      hosts:
       worker-1:
  
    etcd:
      hosts:
        master-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
