build:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n "json_key:${CI_REGISTRY_KEY}" | base64 | tr -d '\n' )\"}}}" > /kaniko/.docker/config.json
    - >
      export TAG=$(if [[ "$CI_COMMIT_TAG"} ]]; then
                      echo ${CI_COMMIT_TAG};
                   else
                      echo ${CI_COMMIT_SHORT_SHA};
                   fi);
      /kaniko/executor \
        --context "${CI_PROJECT_DIR}" \
        --dockerfile "${CI_PROJECT_DIR}/Dockerfile" \
        --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}:${TAG}"
    - echo $TAG
deploy:
  image: bitnami/kubectl:latest
  stage: deploy
  script:
    - sed -i "s/__VERSION__/$CI_COMMIT_TAG/" k8s.yaml
    - kubectl get pod
    - kubectl apply -f k8s.yaml
  only:
    - tags
