apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diplom-app
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diplom-app
  template:
    metadata:
      namespace: gitlab
      labels:
        app: diplom-app
    spec:
      containers:
        - name: diplom-app
          image: cr.yandex/crp87hb9jqfhvvcf3kj7/web-dev/my-diplom-project:__VERSION__
          imagePullPolicy: Always
      imagePullSecrets:
      - name: cr-key-secret
---
apiVersion: v1
kind: Service
metadata:
  name: diplom-app-service
  namespace: gitlab
spec:
  selector:
    app: diplom-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 30080
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: diplom-app-svc
  namespace: gitlab
spec:
  selector:
    app: diplom-app
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-diplom-app
spec:
  rules:
  - host: nginx-service.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: diplom-app-svc
            port:
              number: 80
  ingressClassName: nginx
